### ISSUE TITLE
texture and material problem Tiled2Unity

### ISSUE THREAD

**Issue by moumnimohamed** [Seanba/Tiled2Unity#100]
when i try to export my map to unity ,all the exported map is white , with those erreurs ,
![tiedproblem](https://cloud.githubusercontent.com/assets/21304554/25856624/71d8d792-34ce-11e7-954e-f986d650bcc9.PNG)

![mapsmaps](https://cloud.githubusercontent.com/assets/21304554/25856831/158eaaa6-34cf-11e7-8472-a1933ae81fa8.PNG)

i update the tiled2unity  and i have this other problem

![mapsmaps](https://cloud.githubusercontent.com/assets/21304554/25858496/cb813b54-34d3-11e7-966f-5892efff1d08.PNG)

**Comment by Seanba** [comment]
Hi Moumnimohamed, what version of Windows are you using? I'm seeing similar reports of SkiaSharp throwing an exception but I'm not able to replicate.

**Comment by moumnimohamed** [comment]
i use windows 7 with last version of unity 3d

**Comment by Seanba** [comment]
It's possible Tiled2Unity can no longer run on Windows 7 due to the version of .NET it is using.

But before we get to that: Are you using the 64 bit or 32 bit version of Windows 7? And what version of the .NET Framework do you have installed?

Also, can you send me your Tiled map (and tileset files)? I might as well check that there isn't something special about your map that I haven't taken into account?

**Comment by moumnimohamed** [comment]
![64 bit](https://cloud.githubusercontent.com/assets/21304554/25868978/9132862e-34f6-11e7-90ae-7ae522afe995.PNG)
![net](https://cloud.githubusercontent.com/assets/21304554/25868979/913e7b14-34f6-11e7-943b-3fecf455736e.PNG)

**Comment by Seanba** [comment]
I see no reason why it shouldn't work for you. Tiled2Unity uses .NET Framework 4.5.2 and that should be covered since you have 4.6.2 installed.

Also, your map works fine for me on my Win 10 box so there's nothing special about your map that is breaking things.

![image](https://cloud.githubusercontent.com/assets/6980630/25870320/536a75ae-34c9-11e7-88e1-0bd0d7aa6031.png)

**Comment by Seanba** [comment]
What I might need to do is catch any Skia.Sharp exceptions and disable previewing in that case. That should get things running for you and others. Stay tuned.

**Comment by moumnimohamed** [comment]
ok think you . i will try to fix it

**Comment by moumnimohamed** [comment]
ok i update my windows from 7 to  windows 10 . the Skia.Sharp problem solved but  the first problem  is still , i try to download an old version of tiled2unity but i can't find them.

**Comment by Seanba** [comment]
My best guess is that some texture files have been moved around in your Unity project. Can you export your Unity project and send it to me? (Right click on Assets folder and select "Export Package...")

**Comment by moumnimohamed** [comment]
I am sorry to have you disturbing, exactly the sprite must be on the project on unity. Now it works well, i m excuse again

**Comment by Seanba** [comment]
No worries. FWIW, the latest version of Tiled2Unity does a better job of handling Skia Sharp exceptions. In the worst case, it should disable the previewer instead of crashing.
