### ISSUE TITLE
Cannot load Tiled2Unity prefabs from code

### ISSUE THREAD

**Issue by ltouroumov** [Seanba/Tiled2Unity#13]
Generated prefabs cannot be dynamically loaded by `Resources.Load<GameObject>(string)` since they are not in a `Resources` folder.

**Comment by Seanba** [comment]
Yes, in order to load a resource it must be in a folder named "Resource".

Tiled2Unity does not place prefabs into a resource folder by default because that increases the size of executable -- even if you do not use those resources in your game.

But you can mark up your Tiled map so that Tiled2Unity will make it a resource so it can be loaded and instantiated from scripts: http://www.seanba.com/tiled2unity-files.html
