### ISSUE TITLE
Prefeb loads blurry and with lines

### ISSUE THREAD

**Issue by mrjeremy3341** [Seanba/Tiled2Unity#134]
when i load my tile map into unity it is just all blurry and with a bunch of lines between the tiles. how do i fix this is it is usable? 
![prnt](https://user-images.githubusercontent.com/33188901/32139893-59a2db6c-bc25-11e7-91a0-aa8b458eb6d9.png)

**Comment by Seanba** [comment]
My Jeremy, I'm guessing with a name RGPMaker Mega Tileset that the texture image is quite large and Unity is shrinking the image in order to fit. Check the texture importer settings for that tileset in Unity. By default, Unity has max texture sizes of 2048x2048 but you can increase it to 8192x8192 depending on your target platform.

That shrinking will make your image blurring and will exasperate the problem with seams (those are the lines you're talking about).

Once you get your texture settings under control then you may have the odd seam depending on your camera settings. [This link will help with that](http://tiled2unity.readthedocs.io/en/latest/fixing-seams/). I recommend the solution of putting a border around your tiles but if you've purchased a "Mega" tileset then that will be a pain. In that case, the `--texel-bias` setting approach is the easiest way to get things up and running.

**Comment by mrjeremy3341** [comment]
yeah my tileset was just way to big, upped the texture size and cropped it down to only the tiles i was using. seems to have fixed it all thanks.

**Comment by Seanba** [comment]
Okay, cool. Good luck with your game.
