### ISSUE TITLE
Imported map hide other objects?

### ISSUE THREAD

**Issue by Mecanne** [Seanba/Tiled2Unity#164]
Hi,
When I import a map into Unity, and then into the Scen View, my player gameObject hides behind the imported map. I tried to change Z-Axis of both but I can't solve this problem. I'm a beginner with this and I do not rule out that it's a problem of mine, but I wanted to know if someone else has happened the same. When I import the map, I have't got any error or warning, all seems to be right.
Here I let you some images and gifs of the problem.

https://i.gyazo.com/aad92821e781f98cd6a287dc3ab61e48.mp4
Player properties:
https://i.gyazo.com/4d55f7d570cd6fecf47b3b05b54250f9.png
https://i.gyazo.com/fb1cf132f668e8bab76a35312a32891e.png
Map prefab properties:
https://i.gyazo.com/7237c232c0663703f8e8d935725f2bb2.png

I hope you can give me a solution,
Thanks.

PD: Sorry for my bad english :)

**Comment by seanb-22ct** [comment]
Hi Mecanne, it's probably the sorting layer or order in layer settings on your sprite or on the map itself. I see that you are using a sorting layer `Unit` and with order `1` for your sprite, but what about your map?

**Comment by Mecanne** [comment]
Hi seanb-22ct, thanks for answer!
Here I give you all about the other maps I used.
I also leave the whole project in case you want to keep an eye on it, along with all the generated files together with tiled2unity. 

Map properties:
[https://gyazo.com/04e44777937b4b150cf0e6b49a0d7adb](url)
Project:
[https://mega.nz/#!kxFgEbIJ!5iFkY1fQBw7RBErtBd-GDxFbffYXOqBeEXO-KEdNMTU](url)

Thanks.

**Comment by Seanba** [comment]
Hi again. I see two problems here.

First, you'll want to manage your Tags & Layers in Unity so that Unit is displayed on top of Floor (and Default - which your imported map is using.)

![image](https://user-images.githubusercontent.com/6980630/38963249-9711a6fc-4336-11e8-9565-38527b740f3c.png)

And second, you are using the "depth" shaders which is something I never really got working correctly. The new version of Tiled2Unity I'm working on will improve on this but in the meantime make sure you have depth shaders turned off.

![image](https://user-images.githubusercontent.com/6980630/38963288-c3c39caa-4336-11e8-8fa9-7722ed06794f.png)

Hope that helps.

**Comment by Mecanne** [comment]
Perfect, it was that. Thank you very much for helping me. I'm new with Unity, I thought the layers went from top to bottom, and not the other way. I had not realized the depth option was checked, my mistake. Again, thank you very much!

**Comment by Seanba** [comment]
I'm glad to hear it. Good luck with your game.
