### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by zoms123** [Seanba/Tiled2Unity#187]
SuperTiled2Unity version: 1.4.6, Unity version: 2018.3.9f1
Missing texture asset: ../../Desktop/gfx/Overworld.png

I export the texture but idk what is the problem im frustrated (the other map works but mine not and i dont know why

![Captura de pantalla (433)](https://user-images.githubusercontent.com/51385891/58916243-6a632b80-8723-11e9-8417-da7ba056baa6.png)
)

**Comment by Seanba** [comment]
Hi there, @zoms123. The issue here is that your TSX file is still referencing the `Overworld.png` that in on your desktop and not the file that is in your Unity project.

You can see the path of the PNG file in the error report: `../../Desktop/gfx/Overworld.png`

To fix, open your Unity project's `Overworldqw.tsx` file in Tiled and change the source of the image to the PNG you have right beside your tileset in Unity.

![image](https://user-images.githubusercontent.com/6980630/58968154-2ac82e00-877b-11e9-9648-27e9c3aa2676.png)

And just a quick note that this is the Github repository for Tiled2Unity but you want to be in SuperTiled2Unity instead. :)

**Comment by zoms123** [comment]
thanks!

Missatge de Sean Barton <notifications@github.com> del dia dc., 5 de juny
2019 a les 17:19:
