### ISSUE TITLE
Ability to move the Tiled2Unity folder within my project

### ISSUE THREAD

**Issue by justinluk** [Seanba/Tiled2Unity#2]
Currently I have to keep the Tiled2Unity folder in the root of my Assets folder. This is because when I try to export from Tiled to Unity, the Tiled2Unity utility doesn't think that the Unity package has been installed.

**Comment by zachwhite** [comment]
Agreed, this would be a fantastic feature!

I actually forked the repo in order to add this functionality myself (searching for Tiled2Unity folder in all folders, rather than only at the root), but when Unity 5 came out, I ended up reverting in order to get the latest T2U changes. Support for this out-of-the-box would make keeping my project folder organized a lot easier :)

**Comment by Seanba** [comment]
Hi guys. Sorry for the late reply (life and such) but I just put a new version of Tiled2Unity that allows you to have the Tiled2Unity folder anywhere in your Unity project.

http://www.seanba.com/tiled2unity-files.html

Best,
Seanba

**Comment by justinluk** [comment]
No worries Seanba! Thanks for looking into this - it's really helpful :)

**Comment by zachwhite** [comment]
Awesome! Thanks so much, this'll really help out with keeping the ol' assets folder cleaned up :)
