### ISSUE TITLE
Not finding map after export

### ISSUE THREAD

**Issue by RedEagleMGN** [Seanba/Tiled2Unity#25]
When I export my tiled map via tiled to Unity in Unity 5.0 there is nothing under prefabs I can drag and drop into Unity. 

I finish my map in tiled, save the tiled file (.tmx), open unity, open your program, click Help > Import... then I click File > Open..., chose the map, choose the Tiled2Unity.export.txt as the export destination and click the Big Export Button. 
Going back into Unity I find nothing under prefabs to import. 

Am I doing something wrong?

**Comment by RedEagleMGN** [comment]
I get error CS0234 in Unity itself too btw. The project is an empty project.

**Comment by xDHILEx** [comment]
Hey Red,

While **I** am not sure what the issue is on your end, I've been able to get it working following this process.

1. After downloading the  `Tiled2UnityLite` and `cs-script` zip/7z files and extracting both to my `Downloads` folder ...
2. In Unity3d, do `Assets`>`Import Package`>`Custom Package` and target the `Tiled2Unity.unitypackage`, click yes/accept when you get the popup and you'll see a Tiled2Unity folder in your project's `Assets` folder.
3. cd into the `cs-script` folder in Downloads and type the following `mono ./cscs.exe ../Tiled2UnityLite.cs -s=0.01 ../../Pictures/Game\ Maps/Demo\ Map.tmx /home/xdhilex/Unity3D/RM2KDEV\'s\ 2D\ RPG/Assets/Tiled2Unity`

which breaksdown to `mono`>`./cscs.exe`>`Tiled2UnityLite`>`options`>`.tmx file location`>`Unity3D project destination`

Once you confirm that it's working correctly, you can move the necessary scripts wherever. Hope this helps.

[Tiled2UnityLite](http://www.seanba.com/downloads/Tiled2Unity/Tiled2UnityLite-1.0.1.0.zip "Tiled2UnityLite")
[CS-Script](https://csscriptsource.codeplex.com/downloads/get/1528904 "CS-Script")
[CS-Script on Mono Guide](http://csscript.net/help/CS-Script_on_Mono.html "CS-Script on Mono Guide")

**Comment by Seanba** [comment]
Hi Red, which file is giving you that error and what library is it saying doesn't exist in the namespace? Are you using Visual Studio or MonoDevelop?

It sounds like Unity has created your C# projects with missing references. If so, which project is it? The editor or runtime version?

**Comment by Seanba** [comment]
Red, I think the problem may be due to your platform selection being WebPlayer and that has finally become deprecated enough that Tiled2Unity will no longer work with it (its version of the Mono API is too old and Unity is no longer supporting it).

If you switch to another platform (like PC, Mac & Linux Standalone) will it work?

**Comment by RedEagleMGN** [comment]
Good news, I updated unity and it worked!

**Comment by Seanba** [comment]
Good to hear. I think it may have been because UnityEngine.Assertions was
introduced in Unity 5.1. I'll work around that for other people that may
still be on Unity 5.0.

Some people have ran into a similar problem when the platform is Web
Player. Unfortunately, that's an issue with Unity deprecating that platform
but I have updated Tiled2Unity so users are at least notified when that's
the problem.

**Comment by Dalhen** [comment]
I am trying for 3 hours to find where is my prefab, Unity changed plateform settings...
Thank you for your help :P

**Comment by Seanba** [comment]
Are there any warnings or errors in the console output window in Unity?

**Comment by Topwise** [comment]
If you have this problem, BUT you get no errors and no prefab, you may be doing what I did.

After you hit the B.A. Export button, DO NOT EXIT the Tiled2Unity app. Just click on Unity.

-----
When I realized that I was clicking export, thinking it exported already to the project. I would then close the application. Then i would switch to unity. It does not move your items to unity unless it is still open and you click on unity after exporting.

**Comment by pkenau** [comment]
In my case, I didn't receive any error message, and even so, I can't export my map from tiled to unity using tiled2unity for mac. I tried also the light version and the windows version, even so, the map doesn't is exported. I have tried to change the name of my directories, and even so, I can't export the map. I don't know which I can try to do it. Any ideas?
