### ISSUE TITLE
some render artifacts (lines) in imported prefab

### ISSUE THREAD

**Issue by sawt00th** [Seanba/Tiled2Unity#34]
Hi, Sean.
I am so much grateful to you for the this importer. But recently i discovered some problem after import *.tmx. In my unity project i saw a long line on imported prefab, and they were on 
on the border of a title compound. i am not possible describe it, you could see in pictures
The first pic is view in Unity proj
![unity_viev](https://cloud.githubusercontent.com/assets/14891592/14900343/c6845c0c-0d98-11e6-8b91-d58b5e2a6859.png)
And second pictures is TiledEditor view
![tiled_viev](https://cloud.githubusercontent.com/assets/14891592/14900344/c6886fcc-0d98-11e6-9db4-6e02e86a2509.png)
Pls take me some advice about fix it.
And i want ask you about custom value "Vertex scale" - its field is not save specified value: I wrote "0.01" and pressed BigButExport. Export was been done, but in log-line i saw vertex-scale value as "1.0" - what i didi  wrong?

**Comment by Seanba** [comment]
Hi Nazar, those lines are known as "seams" and it's a command problem with
rendering 2D graphics in 3D pipelines. What is the size of the texture
being used? If it is over 2048x2048 pixels then that could be the cause. It
can also be caused by using a lighting shader. In that case the only way
I've found to fix it is to put a "border" around each tile (see this
tutorial
<http://www.firebelly.net/post/114529965784/tile-gaps-using-unity-5-and-tiled2unity>
).

For "Vertex Scale" that is something you're setting here, right? I just
tried it myself and it worked okay.

[image: Inline image 1]

Best,
Sean

**Comment by sawt00th** [comment]
Yes, i am used map with size over 2048p, but it not at full size now - i need create bigger map...a lot more. So, i will try re-create tile-map with border lines, may be it will good for me. Thank a lot, Sean.

A few words about vertex scale.
Previously, when i was importing tiled-map,  Render Sprites (in the same project) cards had a very small scale and I had each of them to install the Scale-value for X and Y coordinates. I think what I'm doing wrong, and ask to see my thoughts:
If I understand correctly, its constant need for tranpond correctly the ratio of the amount of pixels on the inside Unity value - Units. Also for the correct size of tiles, which are imported have been internally Unity like sprits Render. So. Okey.
I have tiled map with 64x64p size of tile. What is the value of the vertex scale should I choose to equal the size of the map and imported Renden Sprite the same size? And main quuestion - what is Pixel per Unit must be imported Render Sprite.
I can not understand the difference between these values close((
PS. Sorry for a easy questions, i just started work with Unity.

**Comment by Seanba** [comment]
In the latest Tiled2Unity I have made it easier to implement vertex scale by having it be the same as the "Pixels Per Unit" value that you enter for your sprites in Unity.
