### ISSUE TITLE
Properties for individual tiles

### ISSUE THREAD

**Issue by zachwhite** [Seanba/Tiled2Unity#4]
Currently, looks like properties (unity:layer, unity:tag, etc) are only grabbed for actual tile/object layers. I'm currently trying to build our game in such a way that we can do item/enemy placement entirely from within Tiled, but having so many layers becomes cumbersome.

Would be really cool if I could just tag my individual tiles with the unity:tag property (ie: unity:tag = coinSpawner, enemySpawner, etc), and then paint them into a single layer

Not sure if this functionality exists already, and I'm just missing the obvious, but if not, this would be a fantastic feature to have!

**Comment by Seanba** [comment]
Hi Zachary, sorry for the late reply. I have been purposely avoiding
properties on separate tiles because I've been concerned about the O(N^2)
complexity of 2D maps. I see people with 256x256 tiles wondering why there
is a collection of 65 thousand properties in their exported maps ... if you
know what I mean.

But something like this has been a commonly requested feature so I need to
think about how I can deliver on it.

In the meantime, I suggest you look into Tiled's Automapping feature. You
could set up rules in Tiled that take certain tiles from one layer and
automatically generate tiles (or even objects) in another layer for you. I
use the automapping stuff a lot for something like that. I commonly only
draw in one layer in Tiled and have the automapping functionality create
everything else for me.

Best,
Seanba

**Comment by zachwhite** [comment]
Ah! Yeah, after some working around with it, Automap does seem to be a pretty good workaround.

Just wanted to note, when I said "individual tiles," that was probably a bit vague; I didn't actually mean every single tile in the map itself, so much as for each tile in a tileset. Yeouch, that'd be a lot of data packed into the tmx file if every single map tile had properties O_o

Automap will definitely do the trick for now, though. Thanks for the tip!

**Comment by Async0x42** [comment]
This'd be a great feature to add, there's lots of cases where it'd be useful for fast 'painting' of spawner/prefabs without requiring an object layer. I think it should be up to the user to worry about having too many properties, rather than avoid having a useful feature (and relying on Automapping)

It'd greatly simplify using Tiled2Unity for creating levels (combined with custom importers)
