### ISSUE TITLE
Recreate new obj and prefab when load  project without library folder ?

### ISSUE THREAD

**Issue by wangjianpeng** [Seanba/Tiled2Unity#51]
I download project from svn ,then my map prefab that use the msh obj with my custom script will lose, then i find the obj will recreate when open the project without library folder.how can i do prevent import script recprocess to create obj and prefab to recover my exit map prefab when open new project ?

**Comment by Seanba** [comment]
My apologies but I don't understand. Is there a chance you know someone that speaks both our languages that could put your words into English for me?

If it helps, you shouldn't need to build your own version of Tiled2Unity if you just want to use it to import Tiled maps in Unity. You could just [download the tool here](https://seanba.itch.io/tiled2unity) and use it.

**Comment by wangjianpeng** [comment]
Sorry for my unclear words. I had imported a tiledmap to unity by this tool, then their would be some files include map.xml ; map.obj and map.prefab,then i add a test script to map.prefab.now, i push the new project to my git server.at last , i pull files from the server to a new project. then i reopen the project that pulled resource from my  git server. the map prefab will lost previous test script .this is my encounter problem.
now i had resolve it.i ignore all the map.xml files ,and not allowed to push to my git server. and modify the tilemap imported asset post process, when it will recreate mesh and replace the prefab ,it must check whether the specify asset path contains the map.xml. 
I dont't think it's a bug. just find it maybe trouble to my situation.at last , the problem solved. thank you.

**Comment by Seanba** [comment]
No need to apologize. I'm the one limited to one language ;)

Since the prefab is recreated each time a `*.tiled2unity.xml` file is imported you are going to lose any edits you made to the prefab "by hand". This is where Custom Importers come into play. The plan for you would be to create your own Custom Importer that adds components to your prefab automatically as part of the import process.

I talk about Custom Importers more on my blog here:  http://www.seanba.com/megadadadventures.html

Best,
Sean
