### ISSUE TITLE
Create differents GameObject from a 

### ISSUE THREAD

**Issue by serbemas** [Seanba/Tiled2Unity#66]
Hi,

I want to know, how can I create different GameObjects from a same Tile.

For example, in my map I have a tree with two fruits. This two fruits are the same Tile in the map editor. So, when I import the map, a single gameobject is created using the two tiles.
That I need in unity, it that this two fruits be in a different Gameobjects to add components to each gameobject individually. 

How can I do it?

**Comment by drinfernoo** [comment]
I would try creating them on an Object Layer instead, and they should each get their own GameObject.

**Comment by Seanba** [comment]
drinfernoo is right on the money, serbemas. Use Object Layers instead of Tile Layers when you need to do something more complex then draw a tile or collide with it.

Also, if you're going to be adding components and game logic to such objects then you'll probably need some custom importing. You can read about Custom Importers here: http://www.seanba.com/megadadadventures.html
