### ISSUE TITLE
Reimporting my atlas / sprite sheet when exporting

### ISSUE THREAD

**Issue by MistaGoustan** [Seanba/Tiled2Unity#81]
Hello, I just started using Tiled and Tiled2Unity, and am having a bit of trouble. My current project has an atlas sprite sheet that is **split** in unity. When I export my Tiled project to unity it creates my prefab but then makes a complete uncut copy of my sprite sheet to use. I feel like that moving forward this will really slow me down. Is there a way to point the prefabs references to use the sprites in my folder or is that a lot of work that not worth the energy? 

![image](https://cloud.githubusercontent.com/assets/15217463/22678354/6bfae1ac-ecc7-11e6-8202-2abb74c95fa8.png)

![image](https://cloud.githubusercontent.com/assets/15217463/22678357/6fc14844-ecc7-11e6-95d5-54fd30ac6510.png)

**Comment by Seanba** [comment]
Hi there. How are you using that texture in Tiled (before you export)? If that texture looks good in your Tiled maps then it should export to Unity via Tiled2Unity okay.

It looks to me you have that texture both imported into Unity, as a sprite texture and then you are referencing another copy of that texture in your Unity map (but in a different location). That's how you're ending up with the same texture in your Unity project twice. If you are going to share textures between sprites and tiles then I would recommend having that texture imported into your project and then have Tiled use that texture (the one already in your Unity project) as a tilesheet. This way the texture will not be re-imported. In other words, your prefab will indeed reference the "sprite" texture you already have, which I think is what you're asking for (it will be treated as an "Internal Texture" instead of an "Import Texture".

**Comment by Seanba** [comment]
Closing as it's been over a month. Mista, if you're still have an issue let us know.
