### ISSUE TITLE
Mac App Build Error

### ISSUE THREAD

**Issue by brock555** [Seanba/Tiled2Unity#89]
When I try and run the shell script to build the mac app, I get the following error:

`Error: Could not find package: Tiled2Unity.1.0.10.1.unitypackage
Could not replace the unity package`

**Comment by Seanba** [comment]
This is to be expected. In order for the Tiled2Unity unitypackage scripts to be part of the build they need to exported from Unity (see Tiled2Unity -> Export Tiled2Unity Library menu item in Unity) to the build directory.

**Word of warning though:** Once you get past this, depending on your version of Xamarin Studio you may get other errors regarding the System.Drawing.dll or other classes in the System.Drawing namespace. This is because the drawing libs are not provided by Mono or Xamarin and a PITA to update.

**Comment by brock555** [comment]
Okay, thanks. I'll just download the compiled app and save the trouble.

**Comment by Seanba** [comment]
BTW, the latest version of Tiled2Unity now uses the SkiaSharp library instead of System.Drawing.Drawing2D. This should make it easy for anyone to compile their own version of Tiled2UnityMac.
